server:
  port: 9191
spring :
  application :
    name : cloud-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          [/**]:
            allowedHeaders:
              - content-type
            allowedOrigins: "http://localhost:4200/"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: LOGIN-SERVICE
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: LOGIN-SERVICE
                fallbackuri: forward:/loginFallback
        - id: ADDRESS-SERVICE
          uri: lb://ADDRESS-SERVICE
          predicates:
            - Path=/address/**
          filters:
            - name: CircuitBreaker
              args:
                name: ADDRESS-SERVICE
                fallbackuri: forward:/cartFallback
        - id: CARTS-SERVICE
          uri: lb://CARTS-SERVICE
          predicates:
            - Path=/cart/**
        - id: PRODUCTS-SERVICE
          uri: lb://PRODUCTS-SERVICE
          predicates:
            - Path=/product/**
eureka:
  client:
    register-with-eureka : true
    fetch-registry: true
    serviceUrl.defaultZone : http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: hystrix-stream
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000