server:
  port: 9191
  connection-timeout: 300000
spring :
  application :
    name : cloud-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: LOGIN-SERVICE
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: LOGIN-SERVICE
                fallbackuri: forward:/loginFallback
        - id: USER-CONTACTS-SERVICE
          uri: lb://USER-CONTACTS-SERVICE
          predicates:
            - Path=/contact/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-CONTACTS-SERVICE
                fallbackuri: forward:/contactFallback
eureka:
  client:
    register-with-eureka : true
    fetch-registry: true
    serviceUrl.defaultZone : http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000